name: weather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  http: ^1.2.2
  lottie: ^3.1.3

dev_dependencies:

  flutter_launcher_icons: "^0.14.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/eugene.png"
#   min_sdk_android: 21
#   remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/


